### ISSUE TITLE
Responsive Layout for Tab Devices.

### ISSUE THREAD

**Issue by abhibhaw** [Webwiznitr/webwiznitr.github.io#3]
Just Adding a few CSS lines will work.

**Comment by Capt-Titanium** [comment]
heyy! can I work on this issue?

**Comment by ankitgoel25** [comment]
I would like to work on this issue

**Comment by abhibhaw** [comment]
@Capt-Titanium assigned! Go on!!

**Comment by Capt-Titanium** [comment]
@abhibhaw  why did u close the issue?

**Comment by abhibhaw** [comment]
@Capt-Titanium Well that was an urgent issue, and someone fixed it before you! You can try some other repo... We have more similar projects.
