### ISSUE TITLE
Add dark mode button 

### ISSUE THREAD

**Issue by Aniket762** [Webwiznitr/webwiznitr.github.io#4]
Make the site have both light mode and dark mode with a button placed in Navbar.

Share screenshots of the changes being made

**Comment by RajSolai** [comment]
Fine I can do it !

**Comment by Aniket762** [comment]
Hey @RajSolai , great man! Go for it 😁

**Comment by RajSolai** [comment]
Hey @Aniket762 the dark mode is finally done , I would like you to review the push #5 
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/54436424/95202287-bb46d080-07fe-11eb-99d5-01713e640cfc.gif)

**Comment by Aniket762** [comment]
Hi @RajSolai , great work mate 😍!
