### ISSUE TITLE
Modify the UI of Show Projects button in header.

### ISSUE THREAD

**Issue by swagat-das** [Webwiznitr/webwiznitr.github.io#8]
We can modify the button style to make it look better. 
What's your opinion @Aniket762 @irsayvid?

I can try this.

**Comment by Aniket762** [comment]
@swagat-das Sure go for it !

Share the before and after screenshots and if it is good we will surely merge it  .

**Comment by swagat-das** [comment]
Can you add hacktoberfest label in it?

**Comment by swagat-das** [comment]
![xyz](https://user-images.githubusercontent.com/65278694/95332839-95d2c900-08c9-11eb-9462-dbf744b401e2.gif)

I have slightly changed the button style.
Now hovering over it is clearly visible as there is a color change also I have added some border-radius, as well as transition effect to hover: after. 

Check out if it works.

**Comment by abhibhaw** [comment]
Hey @swagat-das, can you please make your linked PR too, so that I can once try your codes!

**Comment by swagat-das** [comment]
Okay, I will.

**Comment by abhibhaw** [comment]
Closes because of #23
